name: Деплой
run-name: ${{ github.actor }} - тест и деплой
on: [push]

permissions:
  contents: write
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - name: Инициализация и установка зависимостей
        run: npm ci

      - name: Проверка линтеров
        run: npm run lint

      - name: Сборка проекта
        run: npm run build

      - name: Сборка историй
        run: npm run build-storybook

      - name: Регистрация токена
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Публикация
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static # или путь к собранному Storybook
