name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.12]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          cache: "npm"

      - name: Инициализация и установка зависимостей
        run: npm ci

      - name: Проверка линтеров
        run: npm run lint

      - name: Сборка проекта
        run: npm run build

      - name: Сборка историй
        run: npm run build-storybook

      - name: Публикация
        run: npm run deploy
